kw/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;

namespace kw.Models
{
    public class Comment
    {
        public int Id { get; set; }

        public string Text { get; set; }

        public DateTime DateTime { get; set; }

        [ForeignKey("ThemeModel")]
        public int ThemeId { get; set; }
        public ThemeModel ThemeModel { get; set; }

        [ForeignKey("IdentityUser")]
        public string UserId { get; set; }
        public IdentityUser User { get; set; }
        
    }
}

kw/Models/ThemeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace kw.Models
{
    public class ThemeModel
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Body { get; set; }

        public DateTime DateTime { get; set; }

        [ForeignKey("IdentityUser")]
        public string UserId { get; set; }
        public IdentityUser User { get; set; }

        public int CommentCount { get; set; }

        public string Name { get; set; }
    }
}

kw/Models/ViewModels/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace kw.Models.ViewModels
{
    public class CommentViewModel
    {
        public IEnumerable<Comment> Comments { get; set; }
    }
}

kw/Controllers/ThemeModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kw.Data;
using kw.Models;
using kw.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace kw.Controllers
{
    public class ThemeModelsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        
        public ThemeModelsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: ThemeModels
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ThemeModel.Include(t => t.User).OrderBy(t => t.DateTime);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ThemeModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var themeModel = await _context.ThemeModel
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.Id == id);

            List<Comment> comments = _context.Comment
                .OrderBy(a => a.DateTime)
                .Where(a => a.ThemeId == id).ToList();
            if (themeModel == null)
            {
                return NotFound();
            }
            CommentsInThemeViewModel viewModel = new CommentsInThemeViewModel()
            {
                Id = themeModel.Id,
                Title = themeModel.Title,
                Body = themeModel.Body,
                DateTime = themeModel.DateTime,
                UserName = themeModel.Name,
                Comments = comments
            };
           

            return View(viewModel);
        }

        // GET: ThemeModels/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: ThemeModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Body")] ThemeViewModel themeModel)
        {
            var user = await _userManager.GetUserAsync(User);

            ThemeModel model = new ThemeModel()
            {
                Title = themeModel.Title,
                Body = themeModel.Body,
                DateTime = DateTime.Now,
                UserId = user.Id,
                User = user,
                Name = user.NormalizedUserName
            };
            if (ModelState.IsValid)
            {
                _context.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(themeModel);
        }

        public PartialViewResult ShowComments(int id)
        {
            List<Comment> comments = _context.Comment
                .OrderBy(a => a.DateTime)
                .Where(a => a.ThemeId == id).ToList();
            CommentViewModel viewModel = new CommentViewModel()
            {
                Comments = comments
            };
            return PartialView("Comments", viewModel);
        }

        public async Task<PartialViewResult> CreateComment(int themeId, string text)
        {
            ThemeModel theme = _context.ThemeModel.FirstOrDefault(t => t.Id == themeId);
            var user = await _userManager.GetUserAsync(User);
            List<Comment> comments = _context.Comment
                .OrderBy(a => a.DateTime)
                .Where(a => a.ThemeId == themeId).ToList();
            CommentViewModel viewModel = new CommentViewModel()
            {
                Comments = comments
            };
            theme.CommentCount += 1;
            if (ModelState.IsValid)
            {
                Comment model = new Comment()
                {
                    UserId = user.Id,
                    Text = text,
                    DateTime = DateTime.Now,
                    ThemeId = theme.Id,
                    ThemeModel = theme,
                    User = user
                };
                _context.Update(theme);
                _context.Add(model);
                await _context.SaveChangesAsync();
            }
            
            return PartialView("Comments", viewModel);
        }

        

        // GET: ThemeModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var themeModel = await _context.ThemeModel.FindAsync(id);
            if (themeModel == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", themeModel.UserId);
            return View(themeModel);
        }

        // POST: ThemeModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Body,DateTime,UserId")] ThemeModel themeModel)
        {
            if (id != themeModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(themeModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ThemeModelExists(themeModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", themeModel.UserId);
            return View(themeModel);
        }

        // GET: ThemeModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var themeModel = await _context.ThemeModel
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (themeModel == null)
            {
                return NotFound();
            }

            return View(themeModel);
        }

        // POST: ThemeModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var themeModel = await _context.ThemeModel.FindAsync(id);
            _context.ThemeModel.Remove(themeModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ThemeModelExists(int id)
        {
            return _context.ThemeModel.Any(e => e.Id == id);
        }
    }
}

kw/Views/ThemeModels/Comments.cshtml
@model kw.Models.ViewModels.CommentViewModel

@foreach (var item in Model.Comments)
{
    
    <td>
        @Html.DisplayFor(modelItem => item.User.NormalizedUserName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Text)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DateTime)
    </td>
}

kw/Views/ThemeModels/Create.cshtml
@model kw.Models.ViewModels.ThemeViewModel


@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>ThemeModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
         
            <div class="form-group">
                @Html.Label("Body", "Body")
                @Html.TextArea("Body", "", 5, 3, new { @class = "form-control"})
                
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

kw/Views/ThemeModels/Delete.cshtml
@model kw.Models.ThemeModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ThemeModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

kw/Views/ThemeModels/Details.cshtml
@model kw.Models.ViewModels.CommentsInThemeViewModel



@{
    ViewData["Title"] = @Html.DisplayFor(model => model.Title);
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ThemeModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            @Html.DisplayNameFor(model => model.Title)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
</div>







    <div class="col-md-4">
        <form asp-controller="ThemeModels" asp-action="CreateComment" method="post" style="display: inline;">
            @Html.Label("Description", "Add answer")
            @Html.TextArea("Description", "", 5, 3, new { @class = "form-control", placeholder = "Add your answer", id = "text" })
            <input type="button" value="AddComment" onclick="AddComment('@Model.Id', '@Model.UserName', '@Model.DateTime')" />
        </form>

    </div>
@foreach (var item in Model.Comments)
{
    <div id="result1" class="my">
        <p>
            @Html.DisplayFor(modelItem => item.User.NormalizedUserName) |  @Html.DisplayFor(modelItem => item.DateTime)
        </p>
        <p> @Html.DisplayFor(modelItem => item.Text)</p>
    </div>
}

    <script>
    function AddComment(themeId, name, date) {
        $.ajax({
            url: '@Url.Action("CreateComment", "ThemeModels")',

            type: 'POST',

            data: { 'themeId': themeId, 'text': $('#text').val() },

            success: $("#result1").append("<div class=" + "my>" +
                "<p>" + name + " | answer date : " + date + "</p>" +
                "<p>" + $('#text').val() + "</p></div>")
        });
    }
    </script>


    <div>
        <a asp-action="Index">Back to List</a>
    </div>

kw/Views/ThemeModels/Edit.cshtml
@model kw.Models.ThemeModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>ThemeModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

kw/Views/ThemeModels/Index.cshtml
@model IEnumerable<kw.Models.ThemeModel>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
@if (SignInManager.IsSignedIn(User))
{
    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CommentCount)
            </th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">@item.Title</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateTime)
                </td>
                <th>
                    @Html.DisplayFor(modelItem => item.CommentCount)
                </th>
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <h3 style="font-size: 20px;">Чтобы увидеть список постов и <br>создать новый нужно зарегистрироваться</h3>
}